### ISSUE TITLE
Atelier Heath out of date

### ISSUE THREAD

**Issue by quanghoc** [atelierbram/syntax-highlighting#1]
I was comparing with this:

https://highlightjs.org/static/demo/

Specifically this file here:

https://highlightjs.org/static/demo/styles/atelier-heath-light.css

For example, in Python, the current one on http://atelierbram.github.io/syntax-highlighting/assets/css/heath.css does not have `meta` class.

What is the quick way to update and compile for CodeMirror? Let's say if I copy CSS from highlightjs.org

**Comment by atelierbram** [comment]
Will look into this very soon, so you can grab it from here. Will let you know when it's done.

**Comment by atelierbram** [comment]
Updated the templates for highlight.js, so they are now up to date with the highlight.js repo.
@quanghoc The link you posted to the `CSS`-file in your example for Python ... a copy and paste error?
Anyway, for CodeMirror one can go to the [output folder](https://github.com/atelierbram/syntax-highlighting/tree/master/atelier-schemes/output/codemirror), no need to compile anything, but I do wonder if the base16-template for CodeMirror is still up to date, since it hasn't changed in quite a while.

**Comment by quanghoc** [comment]
Yes, I realized that CodeMirror template is out of date 

Thanks
